### ISSUE TITLE
follow up `pkgmt version`

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#64]
once we finish #60

- when the `version_file` is an empty file, the error is unclear:

```
AttributeError: 'NoneType' object has no attribute 'group'
```

- error message does not accurately display the location of the customized version file:

```
- [Inconsistent version] Version in  top section in CHANGELOG is '0.1.42dev', but version in __init__.py is '0.1.40dev', fix them so they match
```

**Comment by edublancas** [comment]
since we closed #60, let's work on this one

**Comment by neelasha23** [comment]
Acceptance criteria:
1. If version file is empty or `__version__` string not present, raise `click.ClickException` : `Please add version string in <version_file_path> , e.g., __version__ = '0.1dev'`.
2. Add version file path in error message when versions in version file and changelog do not match.
3. Test cases for both projects with version file in `pyproject.toml` and otherwise.
4. Changelog entry.

**Comment by edublancas** [comment]
> If version file is empty or __version__ string not present, raise click.ClickException : Please add version string in <version_file_path> , e.g., __version__ = '0.1dev'.

here we can do something more generic, there's a function that parses the version value. if such function fails, we can raise an error and tell the user how the format should be


the rest looks good

**Comment by neelasha23** [comment]
Yes I have added generic parsing for raising the error in the PR
